import {
  Inter,
  Play,
  Open_Sans,
  Raleway,
  Source_Code_Pro,
} from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth/AuthContext";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// Inter font
export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--inter",
});

// Play font - specify the weights
export const play = Play({
  weight: ["400", "700"], // Available weights for Play font
  subsets: ["latin"],
  display: "swap",
  variable: "--play",
});

// Open Sans font
export const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--openSans",
});

// Raleway font
export const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--raleway",
});

// Source Code Pro font
export const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  display: "swap",
  variable: "--sourceCodePro",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  image: "/assets/icons/icon-site.webp",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${inter.variable} ${play.variable} ${openSans.variable} ${raleway.variable} ${sourceCodePro.variable}`}
    >
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
